### ISSUE TITLE
示例代码PDF保存部分错误

### ISSUE THREAD

**Issue by PussyCat0700** [FudanNLPLAB/CBook-150K#4]
https://github.com/FudanNLPLAB/CBook-150K/blob/e21a11166e6ee0848194b9593a2a04eda2643da4/BOOK_extract_example_code/book_extraction.py#L116
保存的是mobi结果而非pdf结果；
可以改为：
`fp.write(''.join(page_info).strip())`

**Comment by zzhang0179** [comment]
感谢，我已经修改！
